# Generated by Django 6.0.1 on 2026-02-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_agendafacil', '0005_delete_endereco_usuario_bairro_usuario_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rua',
            new_name='logradouro',
        ),
    ]
