# Generated by Django 6.0.1 on 2026-02-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_agendafacil', '0006_rename_rua_usuario_logradouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CANCELADO', 'Cancelado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('FALTOU', 'Faltou'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ATENDENTE', 'Atendente'), ('ADMIN', 'Admin')], default='CLIENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='feedback_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Avaliação do Cliente')),
                ('nota', models.PositiveIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], verbose_name='Nota')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='login_agendafacil.agendamento')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_recebidos', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
