# Generated by Django 6.0.1 on 2026-02-20 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_agendafacil', '0007_alter_agendamento_status_alter_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data', '-horario']},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atendente',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'ATENDENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou')], default='PENDENTE', max_length=15),
        ),
    ]
