# Generated by Django 6.0.1 on 2026-02-25 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_agendafacil', '0009_feedbackcliente_delete_feedback_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_procedimento', models.TextField(verbose_name='Descrição do Atendimento')),
                ('observacoes_atendimento', models.TextField(blank=True, null=True, verbose_name='Observações do Atendimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='login_agendafacil.agendamento')),
                ('atendente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'ATENDENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
