# Generated by Django 6.0.1 on 2026-02-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_agendafacil', '0010_atendimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='atendente',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou')], default='AGENDADO', max_length=15),
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('atendente', models.ForeignKey(limit_choices_to={'tipo_usuario': 'ATENDENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atendimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'horario'],
                'unique_together': {('data', 'horario', 'atendente')},
            },
        ),
    ]
